_target_: src.models.components.metrics.metrics_wrapper.MetricsWrapper

metrics:
  - _target_: src.models.components.loss_fns.huber_loss.HuberLoss
  - _target_: src.models.components.loss_fns.rmse_loss.RMSELoss
  - _target_: src.models.components.loss_fns.mae_loss.MAELoss
  - _target_: src.models.components.loss_fns.rrmse_loss.RRMSELoss
  - _target_: src.models.components.metrics.r2.RSquared
