_target_: src.models.predictive_model.PredictiveModel
geo_encoder:
  _target_: src.models.components.geo_encoders.geoclip.GeoClipCoordinateEncoder
prediction_head:
  _target_: src.models.components.pred_heads.mlp_regression_head.MLPRegressionPredictionHead
  nn_layers: 2
  hidden_dim: 128
trainable_modules: [prediction_head]
normalize_features: true
metrics: ${metrics}
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
loss_fn:
  _target_: torch.nn.MSELoss
